### ISSUE TITLE
eBay Prices don't appear to be working

### ISSUE THREAD

**Issue by phylaxis** [bedoherty/MagicTCGPriceAPI#3]
I tried testing the eBay pricing with your example URI, `http://magictcgprices.appspot.com/api/ebay/price.json?cardname=Restoration%20Angel&cardset=promo` but it returned an empty set. Is this functionality no longer working?

**Comment by bedoherty** [comment]
I'll try to make some time to look at this in the morning.  I don't actively maintain this project and only troubleshoot reported bugs, so thanks for taking the time to mark this.

**Comment by phylaxis** [comment]
I appreciate it. I'm also looking at it, so if I do figure it out I can update it and submit a pull request if you'd like.

**Comment by starryknight64** [comment]
I created a pull request that might fix this issue (was not tested):
https://github.com/bedoherty/MagicTCGPriceAPI/pull/5

**Comment by bedoherty** [comment]
I merged in starryknight64's changes.  This should fix those issues.  Thanks.

**Comment by starryknight64** [comment]
My change didn't appear to fix the issue. So, I started testing it and found out that between "span" and "class", ebay now has not just one, but two spaces.... ugh... so I created one more pull request. And this time I tested it! https://github.com/bedoherty/MagicTCGPriceAPI/pull/6

**Comment by starryknight64** [comment]
Sorry to be a bother, and thanks for merging in my pull requests, but did the application ever get redeployed with my changes? I'm still seeing the ebay functionality not working.

**Comment by bedoherty** [comment]
I'm currently at work and don't have access to my personal machine, so I can't push any changes to app engine.  I'll comment here when I have it live.
